### ISSUE TITLE
import import org.atnos.eff.all._ doesnt import Error effect

### ISSUE THREAD

**Issue by benhutchison** [atnos-org/eff#90]
It missing from the [standard built ins](https://github.com/atnos-org/eff/blob/master/shared/src/main/scala/org/atnos/eff/package.scala#L9-L22)

Is there a reason for this? Its inconsistent and a bit confusing for newcomers. 

On the other hand, if no one has noticed/complained, yet maybe it suggests dropping Error effect and consolidating around Either effect..

**Comment by etorreborre** [comment]
I'm not sure if there's a particular reason, except that the in the `Error`  effect there is a notion of "f "failure" in addition to "error" and this failure can have any type you want. The way it is structured at the moment doesn't allow the `ErrorCreation` trait be be mixed-in an object because the `F` parameter coding for the failure type has to be specified. An alternative is to move that type parameter to each "constructor": `ok`, `eval`, `error`, `fail` and so on. I can definitely do that.

Do you tend to use this effect with a custom `F` or take the default implementation where `F = String`?

**Comment by dispalt** [comment]
FTR, I never use the default one, so the current behavior is desirable for me.

**Comment by benhutchison** [comment]
I mentioned this the first time I went to use the Error effect. No particular opinions, so I suggest keep ing the current behavior. 

Perhaps worth mentioning if/which effects need to be explicitly imported vs covered by the `all._` imports next time docs are being updated..

**Comment by etorreborre** [comment]
Thanks @benhutchison for the idea, I included a note in the imports section of the user guide about that.
